CREATE TABLE IF NOT EXISTS token_list (
    token_id SERIAL PRIMARY KEY,
    id VARCHAR(255) NOT NULL,
    evm_asset_id INTEGER NOT NULL,
    chain VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    symbol VARCHAR(255),
    display_symbol VARCHAR(255),
    optimized_symbol VARCHAR(255),
    decimals INTEGER,
    logo_url VARCHAR(255),
    protocol_id VARCHAR(255),
    price DOUBLE PRECISION DEFAULT NULL,
    price24h_change DOUBLE PRECISION DEFAULT NULL,
    is_verified BOOLEAN,
    is_core BOOLEAN,
    is_wallet BOOLEAN,
    time_at DOUBLE PRECISION DEFAULT NULL,
    amount DOUBLE PRECISION DEFAULT NULL,
    raw_amount NUMERIC,
    raw_amount_hex_str VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (evm_asset_id) REFERENCES evm_assets_debank_v1(evm_asset_id) ON DELETE CASCADE
);